/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ptit_arp_police;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static ptit_arp_police.ArpDetectForm.checkARPTable;
import static ptit_arp_police.ArpDetectForm.scanARPTable;

/**
 *
 * @author ASUS
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    ImageIcon isAttacked = new ImageIcon("D:\\Java\\PTIT_ARP_POLICE\\src\\ptit_arp_police\\no.png");
    ImageIcon isNone = new ImageIcon("D:\\Java\\PTIT_ARP_POLICE\\src\\ptit_arp_police\\yes.png");
    Log log=new Log();
    ArrayList<IPMAC> old_ip_mac_list=new ArrayList<>();
    ArrayList<IPMAC> new_ip_mac_list=new ArrayList<>();
    public NewJFrame() throws IOException {
        initComponents();
        new_ip_mac_list=scanARPTable();
        new_ip_mac_list=checkARPTable(new_ip_mac_list, new_ip_mac_list, log);
        System.out.print(new_ip_mac_list.size());
        Object data[][]=new Object[new_ip_mac_list.size()][4]; 
        String[] column={"","IP","MAC","LAST SEEN"};
        for (int i=0;i<new_ip_mac_list.size();i++)
        {
            data[i][0]=new_ip_mac_list.get(i).isKT()==true?new ImageIcon("D:\\Java\\PTIT_ARP_POLICE\\src\\ptit_arp_police\\yes.png"):new ImageIcon("D:\\Java\\PTIT_ARP_POLICE\\src\\ptit_arp_police\\no.png");
            data[i][1]=new_ip_mac_list.get(i).getIP();
            data[i][2]=new_ip_mac_list.get(i).getMAC();
            data[i][3]=new_ip_mac_list.get(i).getTime();
        }
        DefaultTableModel model = new DefaultTableModel(data, column)
            {
                //  Returning the Class of each column will allow different
                //  renderers to be used based on Class
                public Class getColumnClass(int column)
                {
                    return getValueAt(0, column).getClass();
                }
                public boolean isCellEditable(int row, int column)
                {
                  return false;//This causes all cells to be not editable
                }

        };
        JTable jt=new JTable(model); 
        //jt.setPreferredScrollableViewportSize(jt.getPreferredSize());
        jt.setCellSelectionEnabled(false);  
        jt.setFocusable(false);
        JScrollPane sp=new JScrollPane(jt);
        this.add(sp);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PTIT_ARP_POLICE");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);

        jToggleButton1.setText("jToggleButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jToggleButton1)
                .addContainerGap(435, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jToggleButton1)
                .addContainerGap(441, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NewJFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
